### PR TITLE
Use bashism to look for `nproc` (instead of failing on MacOS).

### PR DESCRIPTION
**Pull request by VolkerStolz**

### CODE REVIEW

**Review by Harniver — CHANGES_REQUESTED** [review]
Sorry for taking so long, I overlooked this pull request. I cannot merge it as it is, since this version would not set the option on my MacOS computer, where I do have the nproc command available. Maybe you can try whether `which nproc` works?

**Comment by VolkerStolz** [comment]
Interesting. What does `hash nproc` yield in bash on your machine?

**Comment by Harniver** [comment]
No output, and zero exit code which makes the if body to be skipped.


Il mer 22 dic 2021, 12:20 Volker Stolz ***@***.***> ha
scritto:

**Comment by VolkerStolz** [comment]
My bash-foo is weak. The square-brackets are in the way; if you remove them, it should work.

**Comment by Harniver** [comment]
Without the brackets it seems to be working. Could you update the pull request? Otherwise I'll close it and commit the edit myself.

**Pull request merged**
